# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master citest ]
  pull_request:
    branches: [ master citest ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Test bootstrap

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Fetch at least 2 commits so that Iceberg doesn't break
      run: git fetch --unshallow
    
    #generate an ssh key pair for being able to clone bee-dmr
    - name: Generate SSH key pair
      run: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
    
    - name: Setup Debug Session
      uses: csexton/debugger-action@master

    # Runs a single command using the runners shell
    - name: Run tests in bootstrap image
      run: make -C bootstrap bee-dmr test

    - name: XUnit Viewer
      id: xunit-viewer
      uses: AutoModality/action-xunit-viewer@v1.0.1
      with:
        # File/Folder of test results
        results: bootstrap/test-reports # default is test-reports

    - name: Attach the report
      uses: actions/upload-artifact@v1
      with:
        name: upload-result
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
